// Package bootstrap implements the bootstrapping logic: generation of a .go file to
// launch the actual generator and launching the generator itself.
//
// The package may be preferred to a command-line utility if generating the serializers
// from golang code is required.
package bootstrap

import (
	"fmt"
	"go/format"
	"io/ioutil"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
)

const genPackage = "github.com/cyralinc/easyjson/gen"
const pkgWriter = "github.com/cyralinc/easyjson/jwriter"
const pkgLexer = "github.com/cyralinc/easyjson/jlexer"

var buildFlagsRegexp = regexp.MustCompile("'.+'|\".+\"|\\S+")

type Generator struct {
	PkgPath, PkgName string
	Types            []string

	NoStdMarshalers          bool
	SnakeCase                bool
	LowerCamelCase           bool
	OmitEmpty                bool
	DisallowUnknownFields    bool
	SkipMemberNameUnescaping bool

	OutName       string
	BuildTags     string
	GenBuildFlags string

	StubsOnly   bool
	LeaveTemps  bool
	NoFormat    bool
	SimpleBytes bool
}

// writeStub outputs an initial stub for marshalers/unmarshalers so that the package
// using marshalers/unmarshales compiles correctly for boostrapping code.
func (g *Generator) writeStub() error {
	f, err := os.Create(g.OutName)
	if err != nil {
		return err
	}
	defer func() { _ = f.Close() }()

	if g.BuildTags != "" {
		_, _ = fmt.Fprintln(f, "// +build ", g.BuildTags)
		_, _ = fmt.Fprintln(f)
	}
	_, _ = fmt.Fprintln(f, "// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package")
	_, _ = fmt.Fprintln(f, "// compilable during generation.")
	_, _ = fmt.Fprintln(f)
	_, _ = fmt.Fprintln(f, "package ", g.PkgName)

	if len(g.Types) > 0 {
		_, _ = fmt.Fprintln(f)
		_, _ = fmt.Fprintln(f, "import (")
		_, _ = fmt.Fprintln(f, `  "`+pkgWriter+`"`)
		_, _ = fmt.Fprintln(f, `  "`+pkgLexer+`"`)
		_, _ = fmt.Fprintln(f, ")")
	}

	sort.Strings(g.Types)
	for _, t := range g.Types {
		_, _ = fmt.Fprintln(f)
		if !g.NoStdMarshalers {
			_, _ = fmt.Fprintln(f, "func (", t, ") MarshalJSON() ([]byte, error) { return nil, nil }")
			_, _ = fmt.Fprintln(f, "func (*", t, ") UnmarshalJSON([]byte) error { return nil }")
		}

		_, _ = fmt.Fprintln(f, "func (", t, ") MarshalEasyJSON(w *jwriter.Writer) {}")
		_, _ = fmt.Fprintln(f, "func (*", t, ") UnmarshalEasyJSON(l *jlexer.Lexer) {}")
		_, _ = fmt.Fprintln(f)
		_, _ = fmt.Fprintln(f, "type EasyJSON_exporter_"+t+" *"+t)
	}
	return nil
}

// writeMain creates a .go file that launches the generator if 'go run'.
func (g *Generator) writeMain() (path string, err error) {
	f, err := ioutil.TempFile(filepath.Dir(g.OutName), "easyjson-bootstrap")
	if err != nil {
		return "", err
	}

	_, _ = fmt.Fprintln(f, "// +build ignore")
	_, _ = fmt.Fprintln(f)
	_, _ = fmt.Fprintln(f, "// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch")
	_, _ = fmt.Fprintln(f, "// the actual generator.")
	_, _ = fmt.Fprintln(f)
	_, _ = fmt.Fprintln(f, "package main")
	_, _ = fmt.Fprintln(f)
	_, _ = fmt.Fprintln(f, "import (")
	_, _ = fmt.Fprintln(f, `  "fmt"`)
	_, _ = fmt.Fprintln(f, `  "os"`)
	_, _ = fmt.Fprintln(f)
	_, _ = fmt.Fprintf(f, "  %q\n", genPackage)
	if len(g.Types) > 0 {
		_, _ = fmt.Fprintln(f)
		_, _ = fmt.Fprintf(f, "  pkg %q\n", g.PkgPath)
	}
	_, _ = fmt.Fprintln(f, ")")
	_, _ = fmt.Fprintln(f)
	_, _ = fmt.Fprintln(f, "func main() {")
	_, _ = fmt.Fprintf(f, "  g := gen.NewGenerator(%q)\n", filepath.Base(g.OutName))
	_, _ = fmt.Fprintf(f, "  g.SetPkg(%q, %q)\n", g.PkgName, g.PkgPath)
	if g.BuildTags != "" {
		_, _ = fmt.Fprintf(f, "  g.SetBuildTags(%q)\n", g.BuildTags)
	}
	if g.SnakeCase {
		_, _ = fmt.Fprintln(f, "  g.UseSnakeCase()")
	}
	if g.LowerCamelCase {
		_, _ = fmt.Fprintln(f, "  g.UseLowerCamelCase()")
	}
	if g.OmitEmpty {
		_, _ = fmt.Fprintln(f, "  g.OmitEmpty()")
	}
	if g.NoStdMarshalers {
		_, _ = fmt.Fprintln(f, "  g.NoStdMarshalers()")
	}
	if g.DisallowUnknownFields {
		_, _ = fmt.Fprintln(f, "  g.DisallowUnknownFields()")
	}
	if g.SimpleBytes {
		_, _ = fmt.Fprintln(f, "  g.SimpleBytes()")
	}
	if g.SkipMemberNameUnescaping {
		_, _ = fmt.Fprintln(f, "  g.SkipMemberNameUnescaping()")
	}

	sort.Strings(g.Types)
	for _, v := range g.Types {
		_, _ = fmt.Fprintln(f, "  g.Add(pkg.EasyJSON_exporter_"+v+"(nil))")
	}

	_, _ = fmt.Fprintln(f, "  if err := g.Run(os.Stdout); err != nil {")
	_, _ = fmt.Fprintln(f, "    fmt.Fprintln(os.Stderr, err)")
	_, _ = fmt.Fprintln(f, "    os.Exit(1)")
	_, _ = fmt.Fprintln(f, "  }")
	_, _ = fmt.Fprintln(f, "}")

	src := f.Name()
	if err := f.Close(); err != nil {
		return src, err
	}

	dest := src + ".go"
	return dest, os.Rename(src, dest)
}

func (g *Generator) Run() error {
	if err := g.writeStub(); err != nil {
		return err
	}
	if g.StubsOnly {
		return nil
	}

	path, err := g.writeMain()
	if err != nil {
		return err
	}
	if !g.LeaveTemps {
		defer func() { _ = os.Remove(path) }()
	}

	f, err := os.Create(g.OutName + ".tmp")
	if err != nil {
		return err
	}
	if !g.LeaveTemps {
		defer func() { _ = os.Remove(f.Name()) }() // will not remove after rename
	}

	execArgs := []string{"run"}
	if g.GenBuildFlags != "" {
		buildFlags := buildFlagsRegexp.FindAllString(g.GenBuildFlags, -1)
		execArgs = append(execArgs, buildFlags...)
	}
	execArgs = append(execArgs, "-tags", g.BuildTags, filepath.Base(path))
	cmd := exec.Command("go", execArgs...)

	cmd.Stdout = f
	cmd.Stderr = os.Stderr
	cmd.Dir = filepath.Dir(path)
	if err = cmd.Run(); err != nil {
		return err
	}
	_ = f.Close()

	// move unformatted file to out path
	if g.NoFormat {
		return os.Rename(f.Name(), g.OutName)
	}

	// format file and write to out path
	in, err := ioutil.ReadFile(f.Name())
	if err != nil {
		return err
	}
	out, err := format.Source(in)
	if err != nil {
		return err
	}
	return ioutil.WriteFile(g.OutName, out, 0644) // #nosec G306 -- g.OutName is autogenerated code file, 0644 is fine.
}
