name: easyjson

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test with Go ${{ matrix.go }}
    strategy:
      fail-fast: false
      matrix:
        go: [ 1.23 ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Install golint
        if: matrix.go > 1.15
        run: go install golang.org/x/lint/golint@latest

      - name: Build and Run tests
        run: make
